(()=>{
  const BASE='/boarding-base.js?v=47';
  const base=document.createElement('script');base.src=BASE;base.onload=installSafeViewer;base.onerror=()=>console.error('Palma boarding base non disponibile');document.head.appendChild(base);
  function installSafeViewer(){if(document.getElementById('boarding-viewer-safe-v49'))return;const style=document.createElement('style');style.id='boarding-viewer-safe-v49';style.textContent=`
      .boarding-full{padding:0!important;align-items:stretch!important;justify-content:stretch!important}
      .boarding-full .boarding-modal{width:100%!important;height:100dvh!important;min-height:100dvh!important;max-height:100dvh!important;display:flex!important;flex-direction:column!important;overflow:hidden!important;border-radius:0!important}
      .boarding-full .boarding-modal-head{position:relative!important;z-index:100!important;flex:0 0 auto!important;box-sizing:border-box!important;min-height:calc(60px + env(safe-area-inset-top))!important;padding:calc(10px + env(safe-area-inset-top)) calc(66px + env(safe-area-inset-right)) 10px calc(16px + env(safe-area-inset-left))!important;background:#FBF8F3!important;border-bottom:1px solid rgba(18,59,77,.10)!important}
      .boarding-full .boarding-modal-head [data-close]{position:absolute!important;right:calc(10px + env(safe-area-inset-right))!important;top:calc(8px + env(safe-area-inset-top))!important;width:46px!important;height:46px!important;min-width:46px!important;min-height:46px!important;padding:0!important;border:0!important;border-radius:50%!important;display:grid!important;place-items:center!important;background:#123B4D!important;color:#fff!important;font-size:22px!important;font-weight:900!important;line-height:1!important;z-index:102!important;box-shadow:0 5px 18px rgba(18,59,77,.28)!important}
      .boarding-full .boarding-pdf,.boarding-full .boarding-image-stage{flex:1 1 auto!important;min-height:0!important;height:auto!important}
      .boarding-full .boarding-pdf{width:100%!important;border:0!important;display:block!important}
      .boarding-full .boarding-image-stage{overflow:auto!important;-webkit-overflow-scrolling:touch!important}
      .boarding-full .boarding-modal-foot{flex:0 0 auto!important;padding-bottom:calc(12px + env(safe-area-inset-bottom))!important}
      .boarding-safe-close{position:fixed!important;right:calc(10px + env(safe-area-inset-right))!important;top:calc(8px + env(safe-area-inset-top))!important;z-index:10150!important;width:46px!important;height:46px!important;border:0!important;border-radius:50%!important;background:#123B4D!important;color:#fff!important;display:grid!important;place-items:center!important;font:900 22px/1 system-ui!important;box-shadow:0 5px 18px rgba(18,59,77,.30)!important}
    `;document.head.appendChild(style);const ensureClose=()=>document.querySelectorAll('.boarding-full').forEach(overlay=>{if(overlay.querySelector('.boarding-safe-close'))return;const btn=document.createElement('button');btn.type='button';btn.className='boarding-safe-close';btn.textContent='×';btn.setAttribute('aria-label','Chiudi carta d’imbarco');btn.onclick=e=>{e.preventDefault();e.stopPropagation();overlay.querySelector('.boarding-modal-head [data-close]')?.click()};overlay.appendChild(btn)});new MutationObserver(ensureClose).observe(document.documentElement,{subtree:true,childList:true});ensureClose()}
})();

