(()=>{
  const SUPABASE_URL='https://cvdlzwralgtapsigyuko.supabase.co';
  const MEDIA_URL=`${SUPABASE_URL}/functions/v1/trip-media-circle`;
  const STORAGE_URL='https://cvdlzwralgtapsigyuko.storage.supabase.co/storage/v1/upload/resumable/sign';
  const PUBLISHABLE_KEY='sb_publishable_-hqWDIWPIcHNCp4CLih94g_XKsqP29G';
  const BUCKET='ricordi';
  const ACCEPT='image/*,video/*,.heic,.heif,.jpg,.jpeg,.png,.webp,.gif,.mov,.mp4,.m4v,.webm,.3gp,.mkv,.avi,.mts,.m2ts';
  const MOBILE=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);
  const CONCURRENCY=MOBILE?3:4;
  const MAX_PICK=250;
  let tusPromise=null;
  const delay=ms=>new Promise(r=>setTimeout(r,ms));
  const code=()=>localStorage.getItem('palma2026-trip-code')||'';
  const clientId=()=>{let id=localStorage.getItem('palma2026-media-client-id');if(!id){id=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem('palma2026-media-client-id',id)}return id};
  const displayName=()=>{for(const key of ['palma2026-profile','palma2026-profile-name-draft']){const raw=localStorage.getItem(key);if(!raw)continue;try{const p=JSON.parse(raw);if(typeof p==='string'&&p.trim())return p.trim()}catch{}if(raw.trim())return raw.replace(/^\"|\"$/g,'').trim()}return'Partecipante'};
  const kind=file=>{const m=(file.type||'').toLowerCase();if(m.startsWith('image/'))return'image';if(m.startsWith('video/'))return'video';const e=file.name.toLowerCase().match(/\.([a-z0-9]+)$/)?.[1]||'';if(['jpg','jpeg','png','webp','gif','heic','heif','avif','tif','tiff','dng','bmp'].includes(e))return'image';if(['mp4','mov','m4v','webm','3gp','mkv','avi','mts','m2ts'].includes(e))return'video';return''};
  function ensureTus(){if(window.tus?.Upload)return Promise.resolve(window.tus);if(tusPromise)return tusPromise;tusPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://unpkg.com/tus-js-client@4.3.1/dist/tus.min.js';s.crossOrigin='anonymous';s.onload=()=>window.tus?.Upload?resolve(window.tus):reject(new Error('tus_missing'));s.onerror=()=>reject(new Error('tus_load_failed'));document.head.appendChild(s)}).catch(e=>{tusPromise=null;throw e});return tusPromise}
  async function api(payload){let last;for(let a=0;a<3;a++){try{const r=await fetch(MEDIA_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:code(),client_id:clientId(),...payload})});const d=await r.json().catch(()=>({}));if(r.ok)return d;const e=new Error(d?.error||`http_${r.status}`);e.status=r.status;throw e}catch(e){last=e;const s=Number(e?.status||0);if(s&&![408,425,429,500,502,503,504].includes(s))throw e;if(a===2)throw e;await delay(500*(2**a))}}throw last||new Error('api_failed')}
  function tusUpload(file,path,token,mime,onProgress){return ensureTus().then(({Upload})=>new Promise((resolve,reject)=>{const up=new Upload(file,{endpoint:STORAGE_URL,retryDelays:[0,1000,3000,5000,10000],headers:{'x-signature':token,apikey:PUBLISHABLE_KEY},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,chunkSize:6*1024*1024,metadata:{bucketName:BUCKET,objectName:path,contentType:mime||file.type||'application/octet-stream',cacheControl:'31536000'},onError:reject,onProgress:(x,t)=>onProgress?.(t?Math.round(x/t*100):0),onSuccess:()=>resolve(up.url)});up.start()}))}
  function panel(circle,jobs){let p=circle.querySelector('.palma-v2-upload');if(!p){p=document.createElement('div');p.className='palma-v2-upload';const list=circle.querySelector('.pc-upload-list');list?.parentElement?.insertBefore(p,list)}const done=jobs.filter(j=>['done','duplicate'].includes(j.state)).length,failed=jobs.filter(j=>j.state==='failed').length,total=jobs.reduce((s,j)=>s+j.file.size,0),weighted=jobs.reduce((s,j)=>s+j.file.size*(j.p||0)/100,0),pct=total?Math.round(weighted/total*100):0;p.innerHTML=`<div class=\"palma-v2-summary\"><strong>${done===jobs.length?'Caricamento completato':'Caricamento parallelo'}</strong><span>${done}/${jobs.length} · ${pct}%${failed?` · ${failed} errori`:''}</span><i><b style=\"width:${pct}%\"></b></i></div>`+jobs.map(j=>`<div class=\"palma-v2-row ${j.state==='failed'?'failed':''}\"><b>${String(j.file.name).replace(/[&<>]/g,'')}</b><span>${j.label}</span><i><b style=\"width:${j.p||0}%\"></b></i></div>`).join('')}
  function previews(circle,files){circle.querySelector('.palma-v2-preview')?.remove();const b=document.createElement('div');b.className='palma-v2-preview';b.innerHTML=`<strong>${files.length} elementi selezionati</strong><div></div>`;const row=b.querySelector('div');files.slice(0,18).forEach(f=>{const x=document.createElement(kind(f)==='video'?'video':'img');x.src=URL.createObjectURL(f);if(x.tagName==='VIDEO'){x.muted=true;x.playsInline=true;x.preload='metadata'}row.appendChild(x)});const list=circle.querySelector('.pc-upload-list');list?.parentElement?.insertBefore(b,list)}
  async function uploadOne(job,circle,jobs){job.state='uploading';job.label='Preparo…';panel(circle,jobs);const prep=await api({op:'prepare_upload',name:job.file.name,mime:job.file.type||'application/octet-stream',size:job.file.size,kind:kind(job.file),display_name:displayName(),captured_at:job.file.lastModified?new Date(job.file.lastModified).toISOString():null});if(prep.duplicate){job.state='duplicate';job.p=100;job.label='✓ Già presente';return}if(prep.provider!=='supabase')throw new Error('file_oltre_50mb');await tusUpload(job.file,prep.upload_path,prep.upload_token,prep.mime||job.file.type,p=>{job.p=p;job.label=`Carico ${p}%`;panel(circle,jobs)});job.p=100;job.label='Registro…';panel(circle,jobs);await api({op:'commit_upload',provider:'supabase',media_id:prep.media_id,path:prep.upload_path,name:prep.name||job.file.name,mime:prep.mime||job.file.type||'',size:job.file.size,kind:kind(job.file),uploader:displayName(),captured_at:job.file.lastModified?new Date(job.file.lastModified).toISOString():null});job.state='done';job.p=100;job.label='✓ Nel Circle'}
  async function process(circle,files){previews(circle,files);const jobs=files.map(file=>({file,state:'queued',p:0,label:'In coda'}));panel(circle,jobs);let cursor=0;const workers=Array.from({length:Math.min(CONCURRENCY,jobs.length)},async()=>{while(cursor<jobs.length){const j=jobs[cursor++];try{await uploadOne(j,circle,jobs)}catch(e){console.error('Ricordi v2 upload',e);j.state='failed';j.label=String(e?.message||'Caricamento non riuscito').replace('file_oltre_50mb','File oltre 50 MB')}finally{panel(circle,jobs)}}});await Promise.all(workers);const ok=jobs.some(j=>['done','duplicate'].includes(j.state));if(ok)setTimeout(()=>{circle.querySelector('[data-close]')?.click();setTimeout(()=>window.dispatchEvent(new Event('palma-open-circle')),180)},700)}
  const css=document.createElement('style');css.textContent=`.palma-v2-preview{padding:10px 14px;background:#f5f7f6;border-top:1px solid #e8ecea}.palma-v2-preview>strong{font-size:12px;color:#173b45}.palma-v2-preview>div{display:flex;gap:7px;overflow:auto;margin-top:8px}.palma-v2-preview img,.palma-v2-preview video{width:70px;height:70px;object-fit:cover;border-radius:12px;flex:0 0 70px}.palma-v2-upload{padding:0 14px;background:#fff;max-height:34dvh;overflow:auto}.palma-v2-summary,.palma-v2-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:5px 8px;padding:9px 0;border-bottom:1px solid #eef1f0;font-size:11px}.palma-v2-summary{position:sticky;top:0;background:#fff;z-index:3}.palma-v2-summary strong{font-size:12px;color:#173b45}.palma-v2-summary i,.palma-v2-row i{grid-column:1/-1;height:6px;background:#e9efed;border-radius:99px;overflow:hidden}.palma-v2-summary i b,.palma-v2-row i b{display:block;height:100%;background:#2b9a8b;transition:width .15s}.palma-v2-row>b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.palma-v2-row.failed span{color:#a6463b}`;document.head.appendChild(css);
  document.addEventListener('click',event=>{const button=event.target.closest?.('.pc-circle [data-add]');if(!button)return;event.preventDefault();event.stopImmediatePropagation();event.stopPropagation();const circle=button.closest('.pc-circle');if(!circle)return;const input=document.createElement('input');input.type='file';input.multiple=true;input.accept=ACCEPT;input.style.display='none';document.body.appendChild(input);input.onchange=()=>{const files=[...(input.files||[])].slice(0,MAX_PICK).filter(f=>kind(f));input.remove();if(files.length)void process(circle,files)};input.click()},true);
})();