(()=>{
  const SUPABASE_URL='https://cvdlzwralgtapsigyuko.supabase.co';
  const MEDIA_URL=`${SUPABASE_URL}/functions/v1/trip-media-circle`;
  const STORAGE_URL='https://cvdlzwralgtapsigyuko.storage.supabase.co/storage/v1/upload/resumable/sign';
  const PUBLISHABLE_KEY='sb_publishable_-hqWDIWPIcHNCp4CLih94g_XKsqP29G';
  const BUCKET='ricordi';
  const ACCEPT='image/*,video/*,.heic,.heif,.jpg,.jpeg,.png,.webp,.gif,.mov,.mp4,.m4v,.webm,.3gp,.mkv,.avi,.mts,.m2ts';
  const MOBILE=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);
  const CONCURRENCY=MOBILE?3:4;
  const MAX_PICK=250;
  const DIRECT_CHUNK=10*1024*1024;
  const PROXY_CHUNK=12*320*1024;
  let tusPromise=null;
  const delay=ms=>new Promise(r=>setTimeout(r,ms));
  const code=()=>localStorage.getItem('palma2026-trip-code')||'';
  const clientId=()=>{let id=localStorage.getItem('palma2026-media-client-id');if(!id){id=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;localStorage.setItem('palma2026-media-client-id',id)}return id};
  const displayName=()=>{for(const key of ['palma2026-profile','palma2026-profile-name-draft']){const raw=localStorage.getItem(key);if(!raw)continue;try{const p=JSON.parse(raw);if(typeof p==='string'&&p.trim())return p.trim()}catch{}if(raw.trim())return raw.replace(/^\"|\"$/g,'').trim()}return'Partecipante'};
  const kind=file=>{const m=(file.type||'').toLowerCase();if(m.startsWith('image/'))return'image';if(m.startsWith('video/'))return'video';const e=file.name.toLowerCase().match(/\.([a-z0-9]+)$/)?.[1]||'';if(['jpg','jpeg','png','webp','gif','heic','heif','avif','tif','tiff','dng','bmp'].includes(e))return'image';if(['mp4','mov','m4v','webm','3gp','mkv','avi','mts','m2ts'].includes(e))return'video';return''};
  function ensureTus(){if(window.tus?.Upload)return Promise.resolve(window.tus);if(tusPromise)return tusPromise;tusPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='/vendor/dist/tus.min.js?v=431';s.onload=()=>window.tus?.Upload?resolve(window.tus):reject(new Error('tus_missing'));s.onerror=()=>reject(new Error('tus_load_failed'));document.head.appendChild(s)}).catch(e=>{tusPromise=null;throw e});return tusPromise}
  async function api(payload){let last;for(let a=0;a<3;a++){try{const r=await fetch(MEDIA_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:code(),client_id:clientId(),...payload})});const d=await r.json().catch(()=>({}));if(r.ok)return d;const e=new Error(d?.error||`http_${r.status}`);e.status=r.status;throw e}catch(e){last=e;const s=Number(e?.status||0);if(s&&![408,425,429,500,502,503,504].includes(s))throw e;if(a===2)throw e;await delay(500*(2**a))}}throw last||new Error('api_failed')}
  function tusUpload(file,path,token,mime,onProgress){return ensureTus().then(({Upload})=>new Promise((resolve,reject)=>{const up=new Upload(file,{endpoint:STORAGE_URL,retryDelays:[0,1000,3000,5000,10000,20000],headers:{'x-signature':token,apikey:PUBLISHABLE_KEY},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,chunkSize:6*1024*1024,metadata:{bucketName:BUCKET,objectName:path,contentType:mime||file.type||'application/octet-stream',cacheControl:'31536000'},onError:reject,onProgress:(x,t)=>onProgress?.(t?Math.round(x/t*100):0),onSuccess:()=>resolve(up.url)});up.findPreviousUploads().then(previous=>{if(previous.length)up.resumeFromPreviousUpload(previous[0]);up.start()}).catch(reject)}))}
  async function oneDriveChunk(prep,file,start,end,mode){const range=`bytes ${start}-${end-1}/${file.size}`;let last=null;for(let a=0;a<3;a++){try{const direct=mode==='direct';const r=await fetch(direct?prep.upload_url:'/api/upload-chunk',{method:'PUT',headers:direct?{'Content-Range':range}:{'Content-Type':'application/octet-stream','Content-Range':range,'X-Palma-Upload-Url':prep.upload_url},body:file.slice(start,end)});const d=await r.json().catch(()=>({}));if([200,201,202].includes(r.status))return{status:r.status,data:d};last=new Error(d?.error?.message||d?.error||`onedrive_${r.status}`);last.status=r.status;if(![408,425,429,500,502,503,504].includes(r.status))throw last}catch(e){last=e;if(mode==='direct'&&e instanceof TypeError){e.cors=true;throw e}if(a===2||e?.status&&![408,425,429,500,502,503,504].includes(Number(e.status)))throw e}await delay(650*(2**a))}throw last||new Error('onedrive_upload_failed')}
  async function oneDriveUpload(prep,file,onProgress){let start=0,final=null,mode='direct';while(start<file.size){const size=mode==='direct'?DIRECT_CHUNK:PROXY_CHUNK,end=Math.min(start+size,file.size);let out;try{out=await oneDriveChunk(prep,file,start,end,mode)}catch(e){if(mode==='direct'&&(e?.cors||e instanceof TypeError)){mode='proxy';continue}throw e}if(out.status===200||out.status===201)final=out.data;const next=Number(String(out.data?.nextExpectedRanges?.[0]||'').split('-')[0]);start=Number.isFinite(next)&&next>start?next:end;onProgress?.(Math.min(100,Math.round(start/file.size*100)))}if(!final?.id)throw new Error('onedrive_missing_item');return final}
  const safe=value=>String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function panel(circle,jobs){
    let p=circle.querySelector('.palma-v4-upload');
    if(!p){
      p=document.createElement('div');
      p.className='palma-v4-upload';
      circle.appendChild(p);
      circle.querySelector('.pc-cloud')?.setAttribute('hidden','');
      p.addEventListener('click',event=>{
        if(!event.target.closest('.palma-v4-orb'))return;
        p.classList.toggle('open');
        panel(circle,p._palmaJobs||[]);
      });
    }
    p._palmaJobs=jobs;
    const done=jobs.filter(j=>['done','duplicate'].includes(j.state)).length;
    const failed=jobs.filter(j=>j.state==='failed').length;
    const total=jobs.reduce((sum,j)=>sum+j.file.size,0);
    const weighted=jobs.reduce((sum,j)=>sum+j.file.size*(j.p||0)/100,0);
    const pct=total?Math.round(weighted/total*100):0;
    const pending=Math.max(0,jobs.length-done-failed);
    const complete=done===jobs.length;
    p.classList.toggle('complete',complete);
    p.classList.toggle('has-errors',failed>0);
    const rows=jobs.map(j=>'<div class="palma-v4-row '+(j.state==='failed'?'failed':'')+'"><b>'+safe(j.file.name)+'</b><span>'+safe(j.label)+'</span><i><b style="width:'+(j.p||0)+'%"></b></i></div>').join('');
    const orbContent=complete?'✓':String(pct)+'<em>%</em>';
    const badge=pending?'<sup>'+pending+'</sup>':'';
    p.innerHTML='<button type="button" class="palma-v4-orb" style="--progress:'+pct+'" aria-label="Caricamenti: '+pct+'%" aria-expanded="'+p.classList.contains('open')+'"><span>'+orbContent+'</span>'+badge+'</button><div class="palma-v4-detail"><div class="palma-v4-summary"><strong>'+(complete?'Caricamento completato':'Caricamenti')+'</strong><span>'+done+'/'+jobs.length+' · '+pct+'%'+(failed?' · '+failed+' errori':'')+'</span></div>'+rows+'</div>';
  }
  function canvasBlob(canvas,quality=.72){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('thumb_failed')),'image/webp',quality))}
  async function imageThumbnail(file){let source,cleanup=()=>{};if('createImageBitmap'in window){source=await createImageBitmap(file,{imageOrientation:'from-image'})}else{const url=URL.createObjectURL(file),image=new Image();image.src=url;await image.decode();source=image;cleanup=()=>URL.revokeObjectURL(url)}try{const width=source.width||source.videoWidth,height=source.height||source.videoHeight;if(!width||!height)throw new Error('image_dimensions');const scale=Math.min(1,640/Math.max(width,height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));canvas.getContext('2d',{alpha:false}).drawImage(source,0,0,canvas.width,canvas.height);return{blob:await canvasBlob(canvas),width,height,duration_ms:null}}finally{source.close?.();cleanup()}}
  function waitMedia(target,event){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('thumb_timeout')),12000);const ok=()=>{clearTimeout(timer);resolve()};const fail=()=>{clearTimeout(timer);reject(new Error('thumb_media_error'))};target.addEventListener(event,ok,{once:true});target.addEventListener('error',fail,{once:true})})}
  async function videoThumbnail(file){const url=URL.createObjectURL(file),video=document.createElement('video');video.preload='metadata';video.muted=true;video.playsInline=true;video.src=url;try{await waitMedia(video,'loadedmetadata');if(Number.isFinite(video.duration)&&video.duration>.2){video.currentTime=Math.min(1,video.duration*.08);await waitMedia(video,'seeked')}else await waitMedia(video,'loadeddata');const width=video.videoWidth,height=video.videoHeight;if(!width||!height)throw new Error('video_dimensions');const scale=Math.min(1,640/Math.max(width,height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));canvas.getContext('2d',{alpha:false}).drawImage(video,0,0,canvas.width,canvas.height);return{blob:await canvasBlob(canvas,.68),width,height,duration_ms:Math.round((video.duration||0)*1000)||null}}finally{video.removeAttribute('src');video.load();URL.revokeObjectURL(url)}}
  async function makeThumbnail(file){try{return kind(file)==='video'?await videoThumbnail(file):await imageThumbnail(file)}catch(error){console.warn('Ricordi anteprima',error?.message||error);return{blob:null,width:null,height:null,duration_ms:null}}}
  async function uploadOne(job,circle,jobs){
    job.state='uploading';job.label='Preparo…';panel(circle,jobs);
    const prep=await api({op:'prepare_upload',name:job.file.name,mime:job.file.type||'application/octet-stream',size:job.file.size,kind:kind(job.file),display_name:displayName(),captured_at:job.file.lastModified?new Date(job.file.lastModified).toISOString():null});
    if(prep.duplicate){job.state='duplicate';job.p=100;job.label='✓ Già presente';return}
    let itemId=null,meta={blob:null,width:null,height:null,duration_ms:null};
    if(prep.provider==='supabase'){
      const thumbTask=makeThumbnail(job.file).then(async result=>{if(result.blob&&prep.thumb_path&&prep.thumb_token){try{await tusUpload(result.blob,prep.thumb_path,prep.thumb_token,result.blob.type||'image/webp')}catch(error){console.warn('Ricordi upload anteprima',error?.message||error)}}return result});
      const originalTask=tusUpload(job.file,prep.upload_path,prep.upload_token,prep.mime||job.file.type,p=>{job.p=p;job.label='Carico '+p+'%';panel(circle,jobs)});
      [,meta]=await Promise.all([originalTask,thumbTask]);
    }else if(prep.provider==='onedrive'){
      const item=await oneDriveUpload(prep,job.file,p=>{job.p=p;job.label='Carico '+p+'%';panel(circle,jobs)});
      itemId=item?.id||null;
    }else throw new Error('provider_non_supportato');
    job.p=100;job.label='Registro…';panel(circle,jobs);
    await api({op:'commit_upload',provider:prep.provider,media_id:prep.media_id,path:prep.upload_path,item_id:itemId,name:prep.name||job.file.name,mime:prep.mime||job.file.type||'',size:job.file.size,kind:kind(job.file),uploader:displayName(),captured_at:job.file.lastModified?new Date(job.file.lastModified).toISOString():null,width:meta.width,height:meta.height,duration_ms:meta.duration_ms});
    job.state='done';job.p=100;job.label='✓ Nel Circle';
  }
  async function process(circle,files){const jobs=files.map(file=>({file,state:'queued',p:0,label:'In coda'}));panel(circle,jobs);let wake=null;try{wake=await navigator.wakeLock?.request?.('screen')}catch{}const run=async list=>{let cursor=0;const workers=Array.from({length:Math.min(list.limit,list.jobs.length)},async()=>{while(cursor<list.jobs.length){const j=list.jobs[cursor++];try{await uploadOne(j,circle,jobs)}catch(e){console.error('Ricordi v3 upload',j.file?.type,j.file?.size,e);j.state='failed';const body=e?.originalResponse?.getBody?.()||'',raw=String(body||e?.message||'Caricamento non riuscito');j.label=/401|403|unauthor|forbidden/i.test(raw)?'Accesso non valido':/409/.test(raw)?'Sessione scaduta: riprova':/413|too.large/i.test(raw)?'Video troppo grande per il trasferimento':/network|fetch|tus/i.test(raw)?'Connessione interrotta: riprova':raw.replace('onedrive_not_connected','Archivio video non collegato').replace('microsoft_refresh_failed','Connessione OneDrive scaduta').replace('onedrive_missing_item','Video non completato').replace('server_error','Errore server')}finally{panel(circle,jobs)}}});await Promise.all(workers)};const imageJobs=jobs.filter(j=>kind(j.file)==='image'),videoJobs=jobs.filter(j=>kind(j.file)==='video'),imageLimit=videoJobs.length?Math.max(1,CONCURRENCY-1):CONCURRENCY;try{await Promise.all([run({jobs:imageJobs,limit:imageLimit}),run({jobs:videoJobs,limit:1})])}finally{try{await wake?.release?.()}catch{}}const ok=jobs.some(j=>['done','duplicate'].includes(j.state));if(ok)setTimeout(()=>{circle.querySelector('[data-close]')?.click();setTimeout(()=>window.dispatchEvent(new Event('palma-open-circle')),180)},700)}
  const css=document.createElement('style');css.textContent=".pc-circle{position:relative}.palma-v4-upload{position:absolute;z-index:20;top:calc(11px + env(safe-area-inset-top));right:15px}.palma-v4-orb{position:relative;width:46px;height:46px;border:0;border-radius:50%;display:grid;place-content:center;background:conic-gradient(#2b9a8b calc(var(--progress)*1%),#dfe9e6 0);color:#173b45;box-shadow:0 7px 22px rgba(23,59,69,.22)}.palma-v4-orb:before{content:'';position:absolute;inset:4px;border-radius:50%;background:#fff}.palma-v4-orb span,.palma-v4-orb em{position:relative;z-index:1;font-style:normal;font-weight:900;line-height:1}.palma-v4-orb span{font-size:13px}.palma-v4-orb em{font-size:7px;margin-top:1px}.palma-v4-orb sup{position:absolute;z-index:2;right:-4px;top:-4px;min-width:18px;height:18px;padding:0 4px;border-radius:99px;display:grid;place-items:center;background:#173b45;color:#fff;font-size:9px;font-weight:900;border:2px solid #fff}.palma-v4-upload.complete .palma-v4-orb{background:#2b9a8b;color:#2b9a8b}.palma-v4-upload.has-errors .palma-v4-orb{background:conic-gradient(#b45b51 calc(var(--progress)*1%),#f0dedb 0)}.palma-v4-detail{display:none;position:absolute;right:0;top:53px;width:min(82vw,320px);max-height:min(54dvh,420px);overflow:auto;padding:10px 12px;background:rgba(255,255,255,.98);border:1px solid #e0e8e5;border-radius:16px;box-shadow:0 14px 40px rgba(23,59,69,.22)}.palma-v4-upload.open .palma-v4-detail{display:block}.palma-v4-summary,.palma-v4-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:5px 8px;padding:8px 0;border-bottom:1px solid #eef1f0;font-size:11px}.palma-v4-summary{position:sticky;top:-10px;background:#fff;z-index:2}.palma-v4-summary strong{font-size:12px;color:#173b45}.palma-v4-row>b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.palma-v4-row i{grid-column:1/-1;height:5px;background:#e9efed;border-radius:99px;overflow:hidden}.palma-v4-row i b{display:block;height:100%;background:#2b9a8b;transition:width .15s}.palma-v4-row.failed span{color:#a6463b}";document.head.appendChild(css);
  document.addEventListener('click',event=>{const button=event.target.closest?.('.pc-circle [data-add]');if(!button)return;event.preventDefault();event.stopImmediatePropagation();event.stopPropagation();const circle=button.closest('.pc-circle');if(!circle)return;const input=document.createElement('input');input.type='file';input.multiple=true;input.accept=ACCEPT;input.style.position='fixed';input.style.left='-9999px';input.style.top='0';input.style.width='1px';input.style.height='1px';input.style.opacity='0';input.style.pointerEvents='none';document.body.appendChild(input);let handled=false;const cleanup=()=>{if(input.isConnected)input.remove()};input.addEventListener('change',async()=>{if(handled)return;handled=true;const files=Array.from(input.files||[]).slice(0,MAX_PICK).filter(f=>kind(f));if(!files.length){cleanup();return}try{await process(circle,files)}finally{setTimeout(cleanup,1500)}},{once:true});input.addEventListener('cancel',()=>setTimeout(cleanup,300),{once:true});input.click()},true);
})();